name: Run a bash command 

on:
  workflow_dispatch: # run the workflow manually
  push:
    branches: [main]

jobs:
  run_bash_command: 
    name: Run a bash command using github actions # title for the job
    runs-on: ubuntu-latest # 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Run a commands manually
        run:  #run this command
          ls -a

      - name: Run multiple commands manually
        run: | #run this command
          pwd
          ls -a

      - name: Run multiple commands manually
        run: bash scripts/bash.sh